# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90875af997978df84793cdd1360fe28b4a6fa90ececd7286e892992c8bcdeebfa258e6555cfa833fb77b30996d36a251a2c43e3d95393e50a53c34ffc5fe610

test:
  secret_key_base: d90875af997978df84793cdd1360fe28b4a6fa90ececd7286e892992c8bcdeebfa258e6555cfa833fb77b30996d36a251a2c43e3d95393e50a53c34ffc5fe610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d90875af997978df84793cdd1360fe28b4a6fa90ececd7286e892992c8bcdeebfa258e6555cfa833fb77b30996d36a251a2c43e3d95393e50a53c34ffc5fe610
